/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.quizia.frontend;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // No meaningful unit test for JavaFX Application entry point
    @Test void appLaunches() {
        // This is a placeholder test to keep the test suite green.
        assertTrue(true);
    }
}
